### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tra38** [enkiv2/ggc#1]
I am unsure whether the GGC is meant to be freeware (where you can use the program for whatever you want, but you are not allowed to add any additional features and distribute them to others), or open source (if you intend to allow people to contribute their own changes and versions to GGC, or to create their own forks).

If it is the latter, I would recommend adding a license so people know how they can contribute to the project, without fear of legal liability in the future.

I understand that it is a bit silly to have a License that is likely going to have more lines than the actual code itself, but the consequences seem okay. You could also provide a link to your preferred license if you want.

**Comment by enkiv2** [comment]
Fixed in https://github.com/enkiv2/ggc/commit/fd1dc19b64b2b17e0d8311310b25b0c29cd69649
